config/routes.rb
Rails.application.routes.draw do

  root "events#index"

  resources :events
  resources :domains
  resources :users
  resource :session

  get 'signin' => 'sessions#new', as: 'signin'
  get 'signup' => 'users#new', as: 'signup'
  get 'dashboard' => 'events#index', as: 'dashboard'

end

app/models/domain.rb
# == Schema Information
#
# Table name: domains
#
#  id         :integer          not null, primary key
#  url        :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Domain < ActiveRecord::Base
  belongs_to :user

  validates :url, presence: true,
                  uniqueness: { case_sensitive: false }
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  created_on :date
#  user_id    :integer
#  source_url :string
#

class Event < ActiveRecord::Base
  belongs_to :user
  has_many :properties, dependent: :destroy

  validates :name, presence: true, length: { minimum: 5 }

 before_create :set_created_on

  DATE_RANGE = [
    'Today',
    'Yesterday',
    'Last week',
    'Last month',
    'Last 3 month',
    'Last 6 month',
    'Last 9 month',
    'Last year'
  ]

  private

  def set_created_on
    self.created_on = Date.today
  end

end

app/models/property.rb
# == Schema Information
#
# Table name: properties
#
#  id         :integer          not null, primary key
#  key        :string
#  value      :string
#  event_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Property < ActiveRecord::Base
  belongs_to :event
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string
#  password_digest :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  has_secure_password
  has_many :events, dependent: :destroy
  has_many :domains, dependent: :destroy

  def self.authenticate(email, password)
    user = User.find_by(email: email)
    user && user.authenticate(password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def require_signin
    unless current_user
      redirect_to signin_path
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def current_user?(user)
    current_user == user
  end

  helper_method :current_user?

  def require_correct_user
    @user = User.find(params[:id])
    unless current_user?(@user)
      redirect_to root_path
    end
  end

  helper_method :require_correct_user

end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  before_action :require_signin, only: [:index]
  # before_action :require_correct_user, only: [:edit, :update, :destroy]
  before_action :set_user
  respond_to :js, only: [:destroy]

  def index
    @domains = @user.domains
    # binding.pry
  end

  def new
    @domain = @user.domains.new
  end

  def create
    @domain = @user.domains.new(domain_params)
    if @domain.save
      redirect_to domains_path
    else
      render :new
    end
  end

  def destroy
    # finish this
    @domains = @user.domains
    @domain = @user.domains.find(params[:id])
    @domain.destroy

    respond_with(@domain) do |format|
      format.html { redirect_to domains_path }
    end
  end

  def edit
    @domain = @user.domains.find(params[:id])
  end

  def update
    @domain = @user.domains.find(params[:id])
      if @domain.update(domain_params)
        redirect_to domains_path
      else
        render :edit
      end
  end

private

  def set_user
    @user = User.find(current_user.id)
  end

  def domain_params
    params.require(:domain).permit(:url)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_filter :verify_authenticity_token
  respond_to :html, :json

  before_action :require_signin, only: [:index]

  def index
    @events = current_user.events
    @event_names = current_user.events.select(:name).group(:name)
    event_name = params[:event_name]
    @init_date_from = 7.days.ago
    @init_date_to = Date.today

    unless params[:date_start].blank? && params[:date_end].blank?
      @date_from = Date.new(params[:date_start][:year].to_i, params[:date_start][:month].to_i, params[:date_start][:day].to_i)
      @date_to = Date.new(params[:date_end][:year].to_i, params[:date_end][:month].to_i, params[:date_end][:day].to_i)
    end

    unless params[:event_name].blank?
      @chart = @events.select(:created_on).group(:created_on)
                      .where(name: event_name)
                      .where('created_on >= ?', @date_from)
                      .where('created_on <= ?', @date_to)
                      .count
    end
  end

  def new
    @event = Event.new
  end

  def create
    domain = Domain.find_by(url: params[:event][:source_url])

    if domain.blank?
      return render text: "This domain name doesn't exist!", status: :bad_request
    end

    user = User.find(domain.user_id)
    @event = user.events.new(event_params)
    properties = params[:event][:properties].map { |k,v| Property.new(key: k, value: v) }
    @event.properties = properties

    if @event.save
      head :created
    else
      render :json => @event.errors, :status => :bad_request
    end
  end

private

  def event_params
    params.require(:event).permit(:name, :source_url, :created_on)
  end

  def properties_params
    params.require(:event).permit(:properties)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    if user = User.authenticate(params[:email], params[:password])
      session[:user_id] = user.id
      redirect_to dashboard_path
    else
      flash.now[:alert] = "Invalid email/password combination!"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to signin_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_signin, except: [:new, :create]
  before_action :require_correct_user, only: [:edit, :update, :destroy]

  def index
    # @users = User.all
    redirect_to user_path(current_user)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to dashboard_path
      # flash[notice] = 'Your password has been changed successfully.'
    else
      render :edit
    end
  end

private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user

  end
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def disable_email?
    if current_user
      true
    else
      false
    end
  end

  def submit_text(user)
    if user.new_record?
      "Sign up"
    else
      "Change password"
    end
  end
end

app/views/domains/_form.html.haml
= simple_form_for @domain do |f|
  = f.input :url, autofocus: true
  .action
    = f.button :submit, class: "btn btn-primary"
    = link_to 'Cancel', domains_path, class: "btn btn-default"

app/views/domains/destroy.html.haml
%h1 Domains#destroy

app/views/domains/destroy.js.erb
var infoBox = '<div class="alert alert-info" style="display:none">Looks like you didn\'t create any domains yet, you can start by <strong><a href="/domains/new">creating your first domain.</a></strong></div>'
<% if @domain.destroyed? %>
  $("#domain-<%= @domain.id %>").fadeOut('slow', function(){
    $(this).remove();
    <% if @domains.blank? %>
      $('.domains .col-md-12').append(infoBox);
      $('.domains .alert').fadeIn();
    <% end %>
  });

<% end %>

app/views/domains/edit.html.haml
.container
  .row
    .col-md-12
      %h1.page-header Edit domain
      = render 'form'

app/views/domains/index.html.haml
.container.domains
  .row
    .col-md-12
      %h1.page-header
        Domain names manager
        = link_to "Add New Domain", new_domain_path, class: 'btn btn-primary pull-right'
      - if @domains.any?
        - @domains.each do |domain|
          %h3(id="domain-#{domain.id}")
            = domain.url
            |
            = link_to "Edit", edit_domain_path(domain)
            |
            = link_to "Delete", domain_path(domain), method: :delete, remote: true, data: {confirm: 'Are you sure?'}
      - else
        .alert.alert-info
          Looks like you didn't create any domains yet, you can start by
          %strong
            = link_to "creating your first domain.", new_domain_path

app/views/domains/new.html.haml
.container
  .row
    .col-md-12
      %h1.page-header Add new domain
      = render 'form'

app/views/events/_chart_area.html.haml
.chart
  - if params[:event_name].blank?
    .alert.alert-info
      %strong Heads up!
      to create a chart please select an event,start date and end date.
  - else
    .well
      = line_chart @chart

app/views/events/_chart_form.html.haml
= form_tag(events_path, {method: :get}) do
  %div
    = label_tag :event_name
    = select_tag :event_name, options_from_collection_for_select(@event_names, "name", "name", :selected => params[:event_name]), prompt: "Choose an event", required: true
  %div
    = label_tag :date_start, 'Start date'
    - if params[:date_start].blank?
      = select_date @init_date_from, prefix: :date_start
    - else
      = select_date @date_from, prefix: :date_start
  %div
    = label_tag :date_end, 'End date'
    - if params[:date_end].blank?
      = select_date @init_date_to, prefix: :date_end
    - else
      = select_date @date_to, prefix: :date_end
  %div
    = submit_tag "Update Chart"

app/views/events/_setup_info.html.haml
.alert.alert-info
  %strong Oh snap! looks like you need to setup Blocmetrics on your web site/app first
  %ol
    %li
      %strong
        = link_to 'Download', 'http://karimtarek.com/track-me/javascripts/blocmetrics.js', target: '_blank'
      blocmetrics javascript micro-library and install it by adding it to your html before the closing body tag, it should look like this:
      %br
      %code
        &lt;script src="/blocmetrics.js"&gt;&lt;/script&gt;
        %br
        &lt;/body&gt;
    %li
      Add the tracking code
      %code blocmetrics.track("event-name", {property-key: "property-value"});
      to any event, for example you can trigger when the page loads or on a link click or hover, it's up to you, you should change
      %code "event-name"
      ,
      %code property-key
      ,
      %code "property-value"
      ,
      %code "property-value"
      to match your desired event criteria, you can have as much event properties as you want, just added to the properties has as a key/value pair, like so:
      %code {property-key-1: "property-value-1", property-key-2: "property-value-2"}
    %li Once the setup is done and users started to interact with your web page, you can then review your events as a chart from the dashboard.

app/views/events/index.html.haml
.container.dashboard
  .row
    .col-md-12
      %h1.page-header Dashboard
      - if current_user.events.any?
        = render 'chart_form'
        = render 'chart_area'
      - else
        = render 'setup_info'

app/views/events/new.html.haml
= simple_form_for @event do |f|
  = f.input :name
  = f.input :tag_name
  = f.input :action
  = f.input :referrer
  = f.button :submit

app/views/layouts/_flash.html.haml
- flash.each do |key, value|
  %div{:class => "alert alert-#{key} alert-dismissible", :role => "alert"}
    %button{:type => 'button', :class => 'close', :'data-dismiss' => 'alert'} &times;
    = value

app/views/layouts/_footer.html.haml
%footer.footer
  .container
    .row
      .col-md-12
        %p
          &copy;
          = Date.today.year
          Blocmetrics

app/views/layouts/_nav.html.haml
%nav(class="navbar navbar-inverse navbar-fixed-top" role="navigation")
  .navbar-header
    %button(type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar")
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar

    = link_to 'Blocmetrics', root_path, class: "navbar-brand"

  %div(id="navbar" class="collapse navbar-collapse pull-right")
    %ul(class="nav navbar-nav")
      - if current_user
        %li.dropdown
          %a{:href => "#", :data => {:toggle => "dropdown"}, :role => "button", :aria => {:expanded => "false"}}(class='dropdown-toggle')
            = current_user.email
            %span.caret
          %ul(class='dropdown-menu' role='menu')
            %li= link_to 'Change password', edit_user_path(current_user)
            %li= link_to 'Manage domains', domains_path
        %li= link_to 'Log Out', session_path, method: :delete
      - else
        - if current_page?(controller: 'sessions', action: 'new') || current_page?('/signin')
          %li= link_to 'Sign up', signup_path
        - else
          %li= link_to 'Sign in', signin_path

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=edge")
    %meta(name="viewport" content="width=device-width, initial-scale=1")
    %title Blocmetrics
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag "//code.highcharts.com/highcharts.js", "chartkick"
    = csrf_meta_tags

  %body
    = render 'layouts/flash'
    = render 'layouts/nav'
    = yield
    = render 'layouts/footer'

app/views/users/_form.html.haml
= simple_form_for @user do |f|
  .form-group
    = f.input :email, autofocus: true, placeholder: 'Email', class: 'form-control', disabled: disable_email?
  .form-group
    = f.input :password, placeholder: 'Password', class: 'form-control'
  .form-group
    = f.input :password_confirmation, placeholder: 'Confirm password', class: 'form-control'
  .action
    = f.submit submit_text(@user), class: "btn btn-primary"
    = link_to 'Cancel', dashboard_path, class: "btn btn-default"

app/views/users/edit.html.haml
.container
  .row
    .col-md-2
      &nbsp;
    .col-md-8
      %h2 Change Password
      = render 'form'
    .col-md-2
      &nbsp;

app/views/users/new.html.haml
.container
  .row
    .col-md-4
      &nbsp;
    .col-md-4
      .well
        %h2 Sign up
        = render 'form'
    .col-md-4
      &nbsp;